FROM ghcr.io/kavanmevada/debootstrap-iso:host-system

RUN mkdir -pv $LFS/{sources,tools}

RUN mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}
RUN for i in bin lib sbin; do ln -sv usr/$i $LFS/$i; done
RUN mkdir -pv $LFS/lib64
RUN chown -v root $LFS/{usr{,/*},lib,var,etc,bin,sbin,tools,sources}
RUN chown -v root $LFS/lib64
