name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u kavanmevada --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}